[phases.setup]
python = "3.11"

[phases.install]
commands = [
    "pip install --upgrade pip"
]

[phases.build]
commands = [
    "pip install -r requirements.txt"
]

[phases.start]
commands = [
    "uvicorn main:app --host 0.0.0.0 --port $PORT"
]
